# Generated by Django 4.1.1 on 2023-08-23 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('featured_image1', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('featured_image2', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('featured_image3', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('featured_image4', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('featured_image5', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='base_post_publish_dbe899_idx'),
        ),
    ]
